// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose
// values do not exceed four million, find the sum of the
// even-valued terms

package main

import "fmt"

func fib() func() int64 {
	var a, b int64 = 1, 0
	return func() int64 {
		a, b = a+b, a
		return a
	}
}

func main() {
	fib_generator := fib()
	var i, sum, max int64 = 0, 0, 4 * 1e6
	for i = 0; i < max; i = fib_generator() {
		if i%2 == 0 {
			sum += i
		}
	}
	fmt.Printf("%d\n", sum)
}
